### ISSUE TITLE
bounds rpthermo bug

### ISSUE THREAD

**Issue by kenza12** [brsynth/rptools#25]
Hi,
There is a bug with rpthermo as you can see with the following command line and error:

```
(rptools_5_13_1) kenza@kenza-Precision-3551:~/Bureau/rptools/rptools$ python3.9 -m rptools.rpthermo ../../synbiocad-galaxy-wrappers/rpThermo/test-data/rp_013_0001.xml test_out --pH '7.5' --ionic_strength '0.25' --pMg '3.0'
usage: rpthermo [-h] [--log ARG] [--log_file LOG_FILE] [--silent] [--version] [--pH [0-14]] [--ionic_strength [0-500]] [--pMg PMG] infile outfile

rpthermo: error: argument --pH: invalid choice: 7.5 (choose from 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)
```
I think that the bounds (min_ph and max_ph) need to be defined as floats too : https://github.com/brsynth/rptools/blob/master/rptools/rpthermo/Args.py#L6

**Comment by breakthewall** [comment]
Ok, removed `choices` argument in Args because you cannot `range` float values.
Push on `dev` branch but still waiting for GitHub to solve the `Segmentation fault` problem on `Test` action.
