### ISSUE TITLE
Use `>>` instead of `&gt;&gt;` in `brsynth:smiles` SBML annotations

### ISSUE THREAD

**Issue by tduigou** [brsynth/rptools#3]
Example:
`[H]C(=C([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])[H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])[H].O=P(O)(O)OP(=O)(O)O.O=P(O)(O)OP(=O)(O)O&gt;&gt;[H]OP(=O)(O[H])OP(=O)(O[H])OC([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])C([H])([H])C([H])=C(C([H])([H])[H])C([H])([H])[H]`

**Comment by breakthewall** [comment]
I think it is not possible since XML recognizes it as a special character. This is why there is conversion in rpSBML.py each time an XML annotation is read.

**Comment by tduigou** [comment]
OK I see.

For the record..

Links:
- https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/46637835#46637835.
- https://www.w3.org/TR/2008/REC-xml-20081126/#syntax

In particular this:
> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and MUST, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.

=> It sounds the use of `>>` might be tolerate but not recommended.

Looking in the code, libsbml converts automatically from `>` to `&gt;` using `libsbml.XMLNode.toXMLString` at the insertion of the value. At the reading the reader needs to be make the translation back, which is done in rpSBML.py.

Since the present situation is the safest way, I close the ticket.
