### ISSUE TITLE
We can't install rptools in 3.9 python environment.

### ISSUE THREAD

**Issue by kenza12** [brsynth/rptools#5]
Trying to install rptools package with the following command:

`mamba install -c conda-forge -c brsynth rptools`

and got this error:

> Looking for: ['rptools=4.4.5']
> 
> pkgs/main/linux-64       [====================] (00m:00s) No change
> pkgs/r/noarch            [====================] (00m:00s) No change
> pkgs/r/linux-64          [====================] (00m:00s) No change
> brsynth/linux-64         [====================] (00m:00s) No change
> brsynth/noarch           [====================] (00m:00s) No change
> pkgs/main/noarch         [====================] (00m:00s) Done
> conda-forge/noarch       [====================] (00m:01s) Done
> conda-forge/linux-64     [====================] (00m:03s) Done
> Encountered problems while solving.
> 
> Problem: package rptools-4.4.5-py39_0 requires cobra, but none of the providers can be installed

Also tested with the following command:

`conda install -c conda-forge -c brsynth rptools`

and got this error : 

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: - 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                                                                                     
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions

**Comment by breakthewall** [comment]
yes, `cobra` needs `bioconda` channel to be installed so the right command is:

`mamba install -c conda-forge -c brsynth -c bioconda rptools`

**Comment by breakthewall** [comment]
Actually, it works with `mamba install -c conda-forge -c brsynth rptools` on macOS Darwin Kernel Version 20.3.0

**Comment by kenza12** [comment]
> 
> 
> yes, `cobra` needs `bioconda` channel to be installed so the right command is:
> 
> `mamba install -c conda-forge -c brsynth -c bioconda rptools`

Ah okay, it works now, thanks !

**Comment by tduigou** [comment]
> Actually, it works with `mamba install -c conda-forge -c brsynth rptools` on macOS Darwin Kernel Version 20.3.0

@breakthewall , on mine (macOS Darwin Kernel Version 20.3.0) it doesn't:
```
conda create -n tmp python=3.9
conda activate tmp
conda install -y -c conda-forge mamba
mamba install -c conda-forge -c brsynth rptools

# Encountered problems while solving:
#   - package rptools-4.2.1-py39_0 requires cobra, but none of the providers can be installed

```

I suspect it works on yours because of the channel configuration (that would include by default the bioconda channel)?
```
conda activate tmp
python -V
# Python 3.9.2
conda config --show channels
# channels:
#   - conda-forge
#   - brsynth
#   - defaults
```

**Comment by breakthewall** [comment]
The commands sequence you put works on mine and yes you're right, this is because I have added bioconda as default channels. So the right command is definitively:

`[mamba|conda] install -c conda-forge -c brsynth -c bioconda rptools`

**Comment by tduigou** [comment]
I dropped a bug report if by any chance it could be fixed, it would be simpler (https://github.com/conda-forge/cobra-feedstock/issues/2).
